;;; cnfonts-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cnfonts.el

(defvar cnfonts-mode nil "\
Non-nil if Cnfonts mode is enabled.
See the `cnfonts-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `cnfonts-mode'.")
(custom-autoload 'cnfonts-mode "cnfonts" nil)
(autoload 'cnfonts-mode "cnfonts" "\
cnfonts mode.

This is a global minor mode.  If called interactively, toggle the
`Cnfonts mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='cnfonts-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'cnfonts-set-font "cnfonts" "\
使用已经保存的字号设置字体.
如果 FRAME 是 non-nil, 设置对应的 FRAME 的字体。

(fn &optional FRAME)" t)
(autoload 'cnfonts-increase-fontsize "cnfonts" "\
Cnfonts 增大字体.

(fn &optional ARG)" t)
(autoload 'cnfonts--next-fontsize "cnfonts" "\
使用下 N 个字号.

(fn N)")
(autoload 'cnfonts-decrease-fontsize "cnfonts" "\
Cnfonts 减小字体.

(fn &optional ARG)" t)
(autoload 'cnfonts-reset-fontsize "cnfonts" "\
使用 `cnfonts-default-fontsize' 重置字号." t)
(autoload 'cnfonts-mouse-wheel "cnfonts" "\
使用 mouse wheel 调整字体大小，类似 `mouse-wheel-text-scale'.

(fn EVENT)" t)
(autoload 'cnfonts-touch-screen-pinch "cnfonts" "\
使用 touch screen pinch 调整字体大小，类似: `touch-screen-pinch'.

(fn EVENT)" t)
(autoload 'cnfonts-switch-profile "cnfonts" "\
切换 cnfonts profile." t)
(autoload 'cnfonts-next-profile "cnfonts" "\
选择下一个字体设置 profile.

(fn &optional _)" t)
(declare-function cnfonts-ui "cnfonts-ui")
(autoload 'cnfonts-regenerate-profile "cnfonts" "\
重新生成当前 profile." t)
(register-definition-prefixes "cnfonts" '("cnfonts-"))


;;; Generated autoloads from cnfonts-ui.el

(register-definition-prefixes "cnfonts-ui" '("cnfonts-ui"))

;;; End of scraped data

(provide 'cnfonts-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cnfonts-autoloads.el ends here
