;;; company-org-block-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-org-block.el

(autoload 'company-org-block "company-org-block" "\
A company completion backend for org blocks.

COMMAND and ARG are sent by company itself.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-org-block" '("company-org-block-"))

;;; End of scraped data

(provide 'company-org-block-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-org-block-autoloads.el ends here
